version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-tests:
    executor:
      name: node/default
    steps:
      -checkout
      -node/install-packages:
        app-dir: ./server
      -node/install-packages:
        app-dir: ./client
      -run:
        command: npm install
        working_directory: ./server
      -run:
        command: npm install
        working_directory: ./client
      -run:
        name: Running server tests
        command: npm test
        working_directory: ./server
      -run:
        name: Running client tests
        command: npm test
        working_directory: ./client
workflows:
  build_and_test:
    jobs:
      - build-and-test

